Use plain sh

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,11 +1,8 @@
-#!/bin/sh
-# Anticonf (tm) script by Jeroen Ooms & Murat Tasan (2017)
-# This script will prefer cflags (specifically includefile dirs) and lib dirs
-# in the following order of precedence:
-#   (1) INCLUDE_DIR or LIB_DIR entered explicitly on the command line, e.g.
-#       R CMD INSTALL --configure-vars='INCLUDE_DIR=/.../include LIB_DIR=/.../lib'
-#   (2) Values found via 'pkg-config' for the libpq package.
-#   (3) Values found via 'pg_config' given a PostgreSQL installation.
+# Anticonf script by Jeroen Ooms (2020)
+# The script will try 'mariadb_config' and 'mysql_config' to find required
+# cflags and ldflags. Make sure this executable is in PATH when installing
+# the package. Alternatively, you can set INCLUDE_DIR and LIB_DIR manually:
+# R CMD INSTALL --configure-vars='INCLUDE_DIR=/.../include LIB_DIR=/.../lib'
 
 # Library settings
 PKG_CONFIG_NAME="libpq"
@@ -18,22 +15,27 @@ PKG_TEST_HEADER="<libpq-fe.h>"
 PKG_LIBS="-lpq"
 
 # pkg-config values (if available)
-if [ $(command -v pkg-config) ]; then
+if [ `command -v mysql_config` ]; then
   PKGCONFIG_CFLAGS=$(pkg-config --cflags --silence-errors ${PKG_CONFIG_NAME})
   PKGCONFIG_LIBS=$(pkg-config --libs --silence-errors ${PKG_CONFIG_NAME})
   PKGCONFIG_MODVERSION=$(pkg-config --modversion --silence-errors ${PKG_CONFIG_NAME})
 
   # MacOS seems to ship a broken libpq.pc file
-  if [[ "$OSTYPE" == "darwin"* ]]; then
-    if [[ "$PKGCONFIG_CFLAGS" == *"Internal.sdk"* ]] || [[ -z "$PKGCONFIG_CFLAGS" ]]; then
-      unset PKGCONFIG_CFLAGS
+  if [ `uname` = "Darwin" ]; then
+    case "$PKGCONFIG_CFLAGS" in
+      *"Internal.sdk"*)
+        unset PKGCONFIG_CFLAGS
+        unset PKGCONFIG_LIBS
+      ;;
+    esac
+    if [ -z "$PKGCONFIG_CFLAGS" ]]; then
       unset PKGCONFIG_LIBS
     fi
   fi
 fi
 
 # pg_config values (if available)
-if [ $(command -v pg_config) ]; then
+if [ `command -v pg_config` ]; then
   PG_INC_DIR=$(pg_config --includedir)
   PG_LIB_DIR=$(pg_config --libdir)
   PG_VERSION=$(pg_config --version)
@@ -56,25 +58,26 @@ elif [ "$PG_INC_DIR" ] || [ "$PG_LIB_DIR" ]; then
   fi
   PKG_CFLAGS="-I${PG_INC_DIR}"
   PKG_LIBS="-L${PG_LIB_DIR} ${PKG_LIBS}"
-elif [[ "$OSTYPE" == "darwin"* ]]; then
-  if [ $(command -v brew) ]; then
-    BREWDIR=$(brew --prefix)
+elif [ `uname` = "Darwin" ]; then
+  brew --version 2>/dev/null
+  if [ $? -eq 0 ]; then
+    BREWDIR=`brew --prefix`
   else
-    curl -sfL "https://jeroen.github.io/autobrew/$PKG_BREW_NAME" > autobrew
-    source autobrew
+    curl -sfL "https://autobrew.github.io/scripts/$PKG_BREW_NAME" > autobrew
+    . ./autobrew
   fi
   PKG_CFLAGS="-I$BREWDIR/opt/$PKG_BREW_NAME/include"
   PKG_LIBS="-L$BREWDIR/opt/$PKG_BREW_NAME/lib $PKG_LIBS"
 fi
 
+# Find compiler
+CC=`${R_HOME}/bin/R CMD config CC`
+CFLAGS=`${R_HOME}/bin/R CMD config CFLAGS`
+CPPFLAGS=`${R_HOME}/bin/R CMD config CPPFLAGS`
+
 # For debugging
 echo "Using PKG_CFLAGS=$PKG_CFLAGS"
 echo "Using PKG_LIBS=$PKG_LIBS"
-
-# Find compiler
-CC=$(${R_HOME}/bin/R CMD config CC)
-CFLAGS=$(${R_HOME}/bin/R CMD config CFLAGS)
-CPPFLAGS=$(${R_HOME}/bin/R CMD config CPPFLAGS)
 
 # Test configuration
 echo "#include $PKG_TEST_HEADER" | ${CC} ${CPPFLAGS} ${PKG_CFLAGS} ${CFLAGS} -E -xc - >/dev/null 2>&1 || R_CONFIG_ERROR=1;
@@ -95,8 +98,10 @@ if [ $R_CONFIG_ERROR ]; then
   echo "If neither can detect $PGK_CONFIG_NAME, you can set INCLUDE_DIR"
   echo "and LIB_DIR manually via:"
   echo "R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'"
-  echo "--------------------------------------------------------------------"
-  exit 1;
+  echo "--------------------------[ ERROR MESSAGE ]----------------------------"
+  cat configure.log
+  echo "-----------------------------------------------------------------------"
+  exit 1
 fi
 
 # Write to Makevars
